sbatch run_train_ada_entro_lambda_2_cifar100_ftrojan_sd42_byol.slurm
sbatch run_train_ada_entro_lambda_2_cifar100_ftrojan_sd42_moco.slurm
sbatch run_train_ada_entro_lambda_2_cifar100_ftrojan_sd42_simclr.slurm
sbatch run_train_ada_entro_lambda_2_cifar100_htba_sd42_byol.slurm
sbatch run_train_ada_entro_lambda_2_cifar100_htba_sd42_moco.slurm
sbatch run_train_ada_entro_lambda_2_cifar100_htba_sd42_simclr.slurm