sbatch run_train_cifar100_ftrojan_sd42_byol_DDP.slurm
sbatch run_train_cifar100_ftrojan_sd42_moco_DDP.slurm
sbatch run_train_cifar100_ftrojan_sd42_simclr_DDP.slurm
sbatch run_train_cifar100_htba_sd42_byol_DDP.slurm
sbatch run_train_cifar100_htba_sd42_moco_DDP.slurm
sbatch run_train_cifar100_htba_sd42_simclr_DDP.slurm